dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  ganache-local:
    verify: False
  polygon-test:
    eth_usd_price_feed: '0x0715A7794a1dc8e42615F059dD6e406A6594651A'
    verify: True
